import {
  Dashboard,
  YourJobs,
  // Candidates,
  Connected,
  Interviews,
  Chat,
  Settings,
  CompanyPage,
  ProfileSearch,
  SupportChat,
  Credits,
  PaymentMethod,
  JobSearch,
  Successfull,
} from "../features/index";

export const DashboardRoutes = [
  {
    path: "/",
    component: Dashboard,
    title: "Dashboard",
    icon: require("../assets/images/sidebar/icons/dashboard-icon.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/my-jobs",
    component: YourJobs,
    title: "My Jobs",
    icon: require("../assets/images/sidebar/icons/find-jobs-icon.svg"),
    exact: true,
    visible: true,
  },
  // {
  //   path: "/candidates",
  //   component: Candidates,
  //   title: "Candidates",
  //   icon: require("../assets/images/sidebar/icons/candidates.svg"),
  //   exact: true,
  //   visible: true,
  // },
  {
    path: "/connected",
    component: Connected,
    title: "Connected",
    icon: require("../assets/images/sidebar/icons/candidates.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/interviews",
    component: Interviews,
    title: "Interviews",
    icon: require("../assets/images/sidebar/icons/Id Card.svg"),
    exact: true,
    visible: false,
  },
  {
    path: "/company",
    component: CompanyPage,
    title: "Company",
    icon: require("../assets/images/sidebar/icons/company-page.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/chat",
    component: Chat,
    title: "Direct Chat",
    icon: require("../assets/images/sidebar/icons/direct-message-icon.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/credits",
    component: Credits,
    title: "Credits",
    icon: require("../assets/images/sidebar/icons/credits.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/profile-search",
    component: ProfileSearch,
    title: "Profile search",
    icon: require("../assets/images/sidebar/icons/profile-search.svg"),
    exact: true,
    visible: false, //disabled for now, will show next month
  },
  {
    path: "/job-search",
    component: JobSearch,
    title: "Job search",
    icon: require("../assets/images/sidebar/icons/settings-icon.svg"),
    exact: true,
    visible: false,
  },
  {
    path: "/settings",
    component: Settings,
    title: "Settings",
    icon: require("../assets/images/sidebar/icons/settings-icon.svg"),
    exact: true,
    visible: true,
  },
  {
    path: "/payment-method",
    component: PaymentMethod,
    title: "Payment Method",
    // icon: require("../assets/images/sidebar/icons/settings-icon.svg"),
    exact: true,
    visible: false,
  },
  {
    path: "/successful",
    component: Successfull,
    title: "Successfull",
    /*icon: require("../assets/images/sidebar/icons/settings-icon.svg"),*/
    exact: true,
    visible: false,
  },
];
